/**
 * Security policy for the generated report.
 *
 * A report is a single self-contained HTML file -- CSV, styles and bundle all
 * inlined -- so a hash-based CSP can deny everything except the exact scripts
 * and styles we built. The hashes are taken over the bytes that end up inline:
 * anything that rewrites those strings after hashing gives a blank page in
 * production only.
 *
 * The policy is emitted twice, because neither delivery mechanism suffices:
 *
 *   1. A `<meta http-equiv="Content-Security-Policy">` tag, which travels with
 *      a report emailed around or opened from disk, and works on GitHub Pages,
 *      which serves static files with fixed headers.
 *
 *   2. A `_headers` file, written by `--headers-file`. GitHub Pages ignores it
 *      -- it is the Cloudflare Pages / Netlify convention -- but it is the only
 *      way to deliver the header-only directives (`frame-ancestors`,
 *      `X-Frame-Options`, `X-Content-Type-Options`).
 *
 * Because `frame-ancestors` is ignored in a `<meta>` tag, clickjacking defense
 * on GitHub Pages falls to the runtime check in `src/frameGuard.ts`.
 *
 * This module is reached from scripts/cli.ts, so it has to stay inside the
 * subset of TypeScript that scriptc compiles statically: no `throw`, no regular
 * expressions, and `createHash().update()` takes the string alone (it hashes
 * UTF-8 either way).
 */
import { createHash } from 'node:crypto';

export function cspHash(source: string): string {
  return `'sha256-${createHash('sha256').update(source).digest('base64')}'`;
}

export interface InlineSources {
  /** Verbatim contents of every inline `<script>` in the document. */
  scripts: string[];
  /** Verbatim contents of every inline `<style>` in the document. */
  styles: string[];
}

function hashList(sources: string[]): string {
  const hashes: string[] = [];
  for (const source of sources) hashes.push(cspHash(source));
  return hashes.join(' ');
}

/**
 * Directives a `<meta>` tag can actually enforce. `frame-ancestors`,
 * `report-uri` and `sandbox` are ignored there -- and listing them anyway just
 * earns a console warning per page load -- so they live in `_headers` instead.
 */
function directives(sources: InlineSources): string[] {
  return [
    `default-src 'none'`,
    // Scripts and stylesheets run only if their contents hash to one of these,
    // so a tampered bundle -- or anything injected into the page -- is dead.
    `script-src ${hashList(sources.scripts)}`,
    `style-src ${hashList(sources.styles)}`,
    // React sets element `style` attributes, which `style-src` hashes cannot
    // cover. It does this through CSSOM, which CSP technically permits, but
    // every assignment logs a violation and drowns out real warnings.
    `style-src-attr 'unsafe-inline'`,
    // The app renders no images; `self` and `data:` only exist so a favicon
    // request doesn't log a violation on every page load.
    `img-src 'self' data:`,
    // Only used by the documented fallback that fetches `/data.csv` from the
    // site itself. Same-origin only: a compromised dependency has nowhere to
    // send the data.
    `connect-src 'self'`,
    `base-uri 'none'`,
    `form-action 'none'`,
    // Deliberately no 'strict-dynamic': it would propagate trust from an
    // allowed script to anything that script loads later, which is exactly the
    // hole the hashes are here to close.
  ];
}

export function contentSecurityPolicy(sources: InlineSources): string {
  return directives(sources).join('; ');
}

export function headersFile(sources: InlineSources): string {
  const csp = directives(sources);
  // Header-only directive: unlike the <meta> copy, this one is enforced.
  csp.push(`frame-ancestors 'none'`);

  return `# Generated by scripts/securityHeaders.ts -- edit it there, not here.
#
# NOTE: GitHub Pages does not read this file. It is written so the policy is
# already correct if the site is ever served by Cloudflare Pages or Netlify.
# On GitHub Pages the <meta> CSP in index.html is what actually applies.
/*
  Content-Security-Policy: ${csp.join('; ')}
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  Referrer-Policy: no-referrer
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin
  Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), microphone=(), payment=(), usb=()
`;
}
